# Generated by Django 4.2.7 on 2026-05-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('coverage_type', models.CharField(choices=[('2g', '2G'), ('3g', '3G'), ('4g', '4G'), ('5g', '5G')], default='4g', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('notes_en', models.TextField(blank=True, default='')),
                ('notes_dari', models.TextField(blank=True, default='')),
                ('notes_pashto', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Coverage areas',
                'ordering': ['province', 'city'],
            },
        ),
        migrations.CreateModel(
            name='InternetPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_dari', models.CharField(blank=True, default='', max_length=200)),
                ('name_pashto', models.CharField(blank=True, default='', max_length=200)),
                ('price_afn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_amount', models.CharField(help_text='e.g. 1GB, 3GB, 10GB', max_length=50)),
                ('validity_days', models.IntegerField(help_text='Number of days the package is valid')),
                ('description_en', models.TextField(blank=True, default='')),
                ('description_dari', models.TextField(blank=True, default='')),
                ('description_pashto', models.TextField(blank=True, default='')),
                ('activation_code', models.CharField(blank=True, default='', help_text='USSD code to activate, e.g. *123*1#', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price_afn'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalSupportFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('network', 'Network Issues'), ('device', 'Device Settings'), ('billing', 'Billing & Payments'), ('account', 'Account Management'), ('other', 'Other')], default='other', max_length=20)),
                ('question_en', models.TextField()),
                ('question_dari', models.TextField(blank=True, default='')),
                ('question_pashto', models.TextField(blank=True, default='')),
                ('answer_en', models.TextField()),
                ('answer_dari', models.TextField(blank=True, default='')),
                ('answer_pashto', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Technical Support FAQ',
                'verbose_name_plural': 'Technical Support FAQs',
                'ordering': ['category', 'question_en'],
            },
        ),
        migrations.AlterField(
            model_name='telecomknowledgebase',
            name='answer_dari',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='telecomknowledgebase',
            name='answer_pashto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='telecomknowledgebase',
            name='question_dari',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='telecomknowledgebase',
            name='question_pashto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
